### ISSUE TITLE
Use zoommtg:// protocol to avoid the extra browser hop

### ISSUE THREAD

**Issue by swinton** [benbalter/zoom-launcher#6]
It should be possible to open Zoom meetings using [the `zoommtg://` protocol](https://support.zoom.us/hc/en-us/articles/202531535-Client-Installation), which will avoid the step of opening the browser.

_Some_ manipulation of the meeting URL will likely be involved.

[This seems to be the spot where the URL manipulation will be required](https://github.com/benbalter/zoom-launcher/blob/b3babcf28b4591c9a06296365f670c30b1899342/lib/zoom_launcher/cli.rb#L28).

:hand: @benbalter happy to submit a PR, if you agree this would be beneficial.

**Comment by benbalter** [comment]
@swinton Great idea! More than glad to review a PR.

**Comment by swinton** [comment]
> More than glad to review a PR

How does #7 look, @benbalter?
